version: '3'

services:
  mysql:
    image: mysql:8.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./scripts/db/db_creation.sql:/docker-entrypoint-initdb.d/db_creation.sql
      - ./scripts/db/db_tenant_test.sql:/docker-entrypoint-initdb.d/db_tenant_test.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql -u ${DB_USER} -h mysql -p${DB_PASSWORD}
      interval: 1s
      retries: 25
  app:
    build: .
    image: multitenant
    environment:
      DB_HOST: mysql
    ports:
      - "3000:3000"
    depends_on:
      mysql: 
        condition: service_healthy
  nginx: 
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./scripts/deploy-pm2/nginx-default:/etc/nginx/sites-available/default
      - ./cert.key:/etc/nginx/cert.key
      - ./cert.crt:/etc/nginx/cert.crt